extern int pasv_enable;
extern int port_enable;
extern unsigned int listen_port;
extern unsigned int max_clients;
extern unsigned int max_per_ip;
extern unsigned int accept_timeout;
extern unsigned int connect_timeout;
extern unsigned int idle_session_timeout;
extern unsigned int local_umask;
extern unsigned int download_max_rate;
extern unsigned int upload_max_rate;
extern const char *listen_address;
